blank_issues_enabled: false
contact_links:
  - name: Commercial Licensing
    url: https://www.linkedin.com/in/timreedcpp/
    about: For commercial use or consulting licensing, contact The Reed Group.
